def get_countries():
    return [
        {
            "country_name": "Japan",
            "city": "Tokyo",
            "country_code": "JP",
            "city_code": "TKO",
            "latitude": 35.6895,
            "longitude": 139.6917,
            "region": "Asia (East)",
        },
        {
            "country_name": "Uzbekistan",
            "city": "Tashkent",
            "country_code": "UZ",
            "city_code": "TAS",
            "latitude": 41.2646,
            "longitude": 69.2163,
            "region": "Asia (Central)",
        },
        {
            "country_name": "Egypt",
            "city": "Cairo",
            "country_code": "EG",
            "city_code": "CAI",
            "latitude": 30.0444,
            "longitude": 31.2357,
            "region": "Africa",
        },
        {
            "country_name": "Germany",
            "city": "Berlin",
            "country_code": "DE",
            "city_code": "BER",
            "latitude": 52.5200,
            "longitude": 13.4050,
            "region": "Europe",
        },
        {
            "country_name": "Brazil",
            "city": "Brasília",
            "country_code": "BR",
            "city_code": "BSB",
            "latitude": -15.7939,
            "longitude": -47.8828,
            "region": "South America",
        },
        {
            "country_name": "United States",
            "city": "New York",
            "country_code": "US",
            "city_code": "NYC",
            "latitude": 40.7128,
            "longitude": -74.0060,
            "region": "North America",
        },
    ]